---
## SCENARIO 1: JOURNAL AND OSD_DATA ON THE SAME DEVICE

- include: ../check_devices.yml

- name: debug ansible_devices
  debug: var=ansible_devices

# NOTE (leseb): the prepare process must be parallelized somehow...
# if you have 64 disks with 4TB each, this will take a while
# since Ansible will sequential process the loop

# NOTE (alahouze): if the device is a partition, the parted command below has
# failed, this is why we check if the device is a partition too.
- name: automatic prepare osd disk(s) without partitions
  command: ceph-disk prepare "/dev/{{ item.key }}"
  ignore_errors: true
  register: prepared_osds
  with_dict: ansible_devices
  when:
    ansible_devices is defined and
    item.value.removable == "0" and
    item.value.partitions|count == 0 and
    journal_collocation and
    osd_auto_discovery

- name: debug combined_parted_results.results
  debug: var=combined_parted_results.results

- name: debug combined_ispartition_results.results
  debug: var=combined_ispartition_results.results

- name: debug journal_collocation
  debug: var=journal_collocation

- name: debug osd_auto_discovery
  debug: var=osd_auto_discovery

- name: manually prepare osd disk(s)
  command: "ceph-disk prepare {{ item.2 }}"
  ignore_errors: true
  with_together:
    - combined_parted_results.results
    - combined_ispartition_results.results
    - devices
  when:
    item.0.rc != 0 and
    item.1.rc != 0 and
    journal_collocation and not
    osd_auto_discovery

- include: ../activate_osds.yml
